package com.yegor.modes.passwordModes;

import com.yegor.interfaces.PasswordMode;

/**
 * This class defines a password for archive
 *
 * @author Yegor Kostochka
 * @version 1.0
 */
public class PasswordModeRealizationHC implements PasswordMode {
    /**
     * General password for archive. It consists of user password and password
     * generated by program (<code>{@link PasswordModeRealizationHC#secondPartOfPassword}</code>).
     */
    private String password;

    /**
     * This password stores to another server. It is the part of the general password
     * (<code>{@link PasswordModeRealizationHC#password}</code>).
     */
    private String secondPartOfPassword;

    /**
     * @return general password for archive
     */
    public String getPassword() {
        return password;
    }

    /**
     * Method generates general password (<code>{@link PasswordModeRealizationHC#password}</code>).
     * It must call method setSecondPartOfPassword().
     * @param userPsw user password
     */
    public void setPassword(String userPsw) {
        setSecondPartOfPassword(userPsw);
        password = userPsw + getSecondPartOfPassword();
    }

    /**
     * @return password stored to another server
     */
    public String getSecondPartOfPassword() {
        return secondPartOfPassword;
    }

    /**
     * Method generates password (part of general <code>{@link PasswordModeRealizationHC#password}</code>)
     * and stores it to another server.
     * @param userPsw parameter for generating <i>secondPartOfPsw</i> password
     */
    public void setSecondPartOfPassword(String userPsw) {
        this.secondPartOfPassword = Integer.toString(userPsw.hashCode());
    }
}
