package interfases;

/**
 * This class defines the mode of password creation.
 *
 * @author Yegor Kostochka
 * @version 1.0
 */
public abstract class CreatePassword {

    /**
     * General password for archive. It consist of user password and password
     * generated by program (password for memcached).
     */
    String psw;

    /**
     * This password stores to memcached. It is the part of the general password (psw).
     */
    String pswToMemcached;

    /**
     * @return general password for archive
     */
    public String getPsw() {
        return psw;
    }

    /**
     * Method generates general password (psw). It must call method setPswToMwmcached().
     * @param psw1 user password
     */
    public abstract void setPsw(String psw1);

    /**
     * @return password stored to memcached
     */
    public String getPswToMemcached() {
        return pswToMemcached;
    }

    /**
     * Method generate password (part of general password) and stores it to memcached.
     * @param pswToMemcached1 parameter for generate <i>pswToMemcached</i> password
     */
    public abstract void setPswToMemcached(String pswToMemcached1);
}
