package actionWithArchive;

import interfases.CreatePassword;

import java.io.File;

/**
 * A class extends class Archive with two methods which defines how password will be set.
 *
 * @author Yegor Kostochka
 * @version 1.0
 */
public class ArchivePsw1 extends Archive implements CreatePassword {

    /**
     * General password for archive. It consist of user password and password
     * generated by program (password for memcached).
     */
    protected String psw;

    /**
     * This password stores to memcached. It is the part of the general password (psw).
     */
    protected String pswToMemcached;

    /**
     * @return general password for archive
     */
    public String getPsw(String userPsw) {
        return psw = userPsw + getPswToMemcached(userPsw);
    }

    /**
     * Method generates general password (psw). It must call method setPswToMwmcached().
     * @param userPsw user password
     */
    public void setPsw(String userPsw) {
        setPswToMemcached(userPsw);
        psw = userPsw + getPswToMemcached(userPsw);
    }

    /**
     * @return password stored to memcached
     */
    public String getPswToMemcached(String userPws) {
        return pswToMemcached;
    }

    /**
     * Method generate password (part of general password) and stores it to memcached.
     * @param pswToMemcached1 parameter for generate <i>pswToMemcached</i> password
     */
    public void setPswToMemcached(String pswToMemcached1) {
        pswToMemcached = Integer.toString(pswToMemcached1.hashCode());
    }


    /**
     * Creates archive file with password and than stores it to assigned path
     *
     * @param file          the file or directory will be written
     * @param pathToArchive path where archive file will be store
     */
    @Override
    public void createArchive(String file, String pathToArchive) {
        getTypeOfArchive().packArchive(new File(file), new File(pathToArchive), psw);
    }

    /**
     * Extracts contents from archive file
     *
     * @param file       the archive file
     * @param pathToFile path where extracting contents will be store
     */
    @Override
    public void extractFromArchive(String file, String pathToFile) {
        getTypeOfArchive().unpackArchive(new File(file), new File(pathToFile), psw);
    }
}
